//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.16 at 01:09:19 PM BRST 
//


package com.grailsfusioncharts.column3d;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for graph complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="graph">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}set" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="caption" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="yAxisName" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="numberPrefix" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="decimalPrecision" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="divlinedecimalPrecision" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="limitsdecimalPrecision" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="inDecimalSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default="," />
 *       &lt;attribute name="inThousandSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default="." />
 *       &lt;attribute name="decimalSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default="," />
 *       &lt;attribute name="thousandSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default="." />
 *       &lt;attribute name="palette" type="{http://www.w3.org/2001/XMLSchema}string" default="2" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "graph", propOrder = {
    "set"
})
public class Graph {

    @XmlElement(required = true)
    protected List<Set> set;
    @XmlAttribute
    protected String caption;
    @XmlAttribute
    protected String yAxisName;
    @XmlAttribute
    protected String numberPrefix;
    @XmlAttribute
    protected String decimalPrecision;
    @XmlAttribute
    protected String divlinedecimalPrecision;
    @XmlAttribute
    protected String limitsdecimalPrecision;
    @XmlAttribute
    protected String inDecimalSeparator;
    @XmlAttribute
    protected String inThousandSeparator;
    @XmlAttribute
    protected String decimalSeparator;
    @XmlAttribute
    protected String thousandSeparator;
    @XmlAttribute
    protected String palette;

    /**
     * Gets the value of the set property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the set property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Set }
     * 
     * 
     */
    public List<Set> getSet() {
        if (set == null) {
            set = new ArrayList<Set>();
        }
        return this.set;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        if (caption == null) {
            return "";
        } else {
            return caption;
        }
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Gets the value of the yAxisName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYAxisName() {
        if (yAxisName == null) {
            return "";
        } else {
            return yAxisName;
        }
    }

    /**
     * Sets the value of the yAxisName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYAxisName(String value) {
        this.yAxisName = value;
    }

    /**
     * Gets the value of the numberPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberPrefix() {
        if (numberPrefix == null) {
            return "";
        } else {
            return numberPrefix;
        }
    }

    /**
     * Sets the value of the numberPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberPrefix(String value) {
        this.numberPrefix = value;
    }

    /**
     * Gets the value of the decimalPrecision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalPrecision() {
        if (decimalPrecision == null) {
            return "0";
        } else {
            return decimalPrecision;
        }
    }

    /**
     * Sets the value of the decimalPrecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalPrecision(String value) {
        this.decimalPrecision = value;
    }

    /**
     * Gets the value of the divlinedecimalPrecision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivlinedecimalPrecision() {
        if (divlinedecimalPrecision == null) {
            return "0";
        } else {
            return divlinedecimalPrecision;
        }
    }

    /**
     * Sets the value of the divlinedecimalPrecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivlinedecimalPrecision(String value) {
        this.divlinedecimalPrecision = value;
    }

    /**
     * Gets the value of the limitsdecimalPrecision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLimitsdecimalPrecision() {
        if (limitsdecimalPrecision == null) {
            return "0";
        } else {
            return limitsdecimalPrecision;
        }
    }

    /**
     * Sets the value of the limitsdecimalPrecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLimitsdecimalPrecision(String value) {
        this.limitsdecimalPrecision = value;
    }

    /**
     * Gets the value of the inDecimalSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInDecimalSeparator() {
        if (inDecimalSeparator == null) {
            return ",";
        } else {
            return inDecimalSeparator;
        }
    }

    /**
     * Sets the value of the inDecimalSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInDecimalSeparator(String value) {
        this.inDecimalSeparator = value;
    }

    /**
     * Gets the value of the inThousandSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInThousandSeparator() {
        if (inThousandSeparator == null) {
            return ".";
        } else {
            return inThousandSeparator;
        }
    }

    /**
     * Sets the value of the inThousandSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInThousandSeparator(String value) {
        this.inThousandSeparator = value;
    }

    /**
     * Gets the value of the decimalSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalSeparator() {
        if (decimalSeparator == null) {
            return ",";
        } else {
            return decimalSeparator;
        }
    }

    /**
     * Sets the value of the decimalSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalSeparator(String value) {
        this.decimalSeparator = value;
    }

    /**
     * Gets the value of the thousandSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThousandSeparator() {
        if (thousandSeparator == null) {
            return ".";
        } else {
            return thousandSeparator;
        }
    }

    /**
     * Sets the value of the thousandSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThousandSeparator(String value) {
        this.thousandSeparator = value;
    }

    /**
     * Gets the value of the palette property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPalette() {
        if (palette == null) {
            return "2";
        } else {
            return palette;
        }
    }

    /**
     * Sets the value of the palette property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPalette(String value) {
        this.palette = value;
    }

}
