//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 10:33:42 AM BRT 
//


package com.grailsfusioncharts.piechart;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for graph complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="graph">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}set" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="caption" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="subCaption" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="xAxisName" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="yAxisName" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="rotateYAxisName" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="labelDisplay" type="{http://www.w3.org/2001/XMLSchema}string" default="Rotate" />
 *       &lt;attribute name="slantLabels" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="shownames" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="showvalues" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="decimals" type="{http://www.w3.org/2001/XMLSchema}string" default="2" />
 *       &lt;attribute name="decimalPrecision" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="numberPrefix" type="{http://www.w3.org/2001/XMLSchema}string" default="R$" />
 *       &lt;attribute name="formatNumberScale" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="inDecimalSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default="," />
 *       &lt;attribute name="inThousandSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default="." />
 *       &lt;attribute name="decimalSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default="," />
 *       &lt;attribute name="thousandSeparator" type="{http://www.w3.org/2001/XMLSchema}string" default="." />
 *       &lt;attribute name="numberScaleValue" type="{http://www.w3.org/2001/XMLSchema}string" default="1000,1000,1000" />
 *       &lt;attribute name="numberScaleUnit" type="{http://www.w3.org/2001/XMLSchema}string" default=" Mil, Milhao, Bi" />
 *       &lt;attribute name="yAxisMinValue" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="yAxisMaxValue" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="palette" type="{http://www.w3.org/2001/XMLSchema}string" default="2" />
 *       &lt;attribute name="useRoundEdges" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="legendBorderAlpha" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="bgColor" type="{http://www.w3.org/2001/XMLSchema}string" default="FFFFFF" />
 *       &lt;attribute name="borderColor" type="{http://www.w3.org/2001/XMLSchema}string" default="FFFFFF" />
 *       &lt;attribute name="canvasBgColor" type="{http://www.w3.org/2001/XMLSchema}string" default="FFFFFF" />
 *       &lt;attribute name="alternateHGridColor" type="{http://www.w3.org/2001/XMLSchema}string" default="FFFFFF" />
 *       &lt;attribute name="alternateVGridColor" type="{http://www.w3.org/2001/XMLSchema}string" default="FFFFFF" />
 *       &lt;attribute name="showShadow" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="lineThickness" type="{http://www.w3.org/2001/XMLSchema}string" default="2" />
 *       &lt;attribute name="canvasBorderThickness" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="showPlotBorder" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="canvasBaseDepth" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="showLegend" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="chartBottomMargin" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "graph", propOrder = {
    "set"
})
public class Graph {

    @XmlElement(required = true)
    protected List<Set> set;
    @XmlAttribute
    protected String caption;
    @XmlAttribute
    protected String subCaption;
    @XmlAttribute
    protected String xAxisName;
    @XmlAttribute
    protected String yAxisName;
    @XmlAttribute
    protected String rotateYAxisName;
    @XmlAttribute
    protected String labelDisplay;
    @XmlAttribute
    protected String slantLabels;
    @XmlAttribute
    protected String shownames;
    @XmlAttribute
    protected String showvalues;
    @XmlAttribute
    protected String decimals;
    @XmlAttribute
    protected String decimalPrecision;
    @XmlAttribute
    protected String numberPrefix;
    @XmlAttribute
    protected String numberSuffix;
    @XmlAttribute
    protected String formatNumberScale;
    @XmlAttribute
    protected String inDecimalSeparator;
    @XmlAttribute
    protected String inThousandSeparator;
    @XmlAttribute
    protected String decimalSeparator;
    @XmlAttribute
    protected String thousandSeparator;
    @XmlAttribute
    protected String numberScaleValue;
    @XmlAttribute
    protected String numberScaleUnit;
    @XmlAttribute
    protected String yAxisMinValue;
    @XmlAttribute
    protected String yAxisMaxValue;
    @XmlAttribute
    protected String palette;
    @XmlAttribute
    protected String useRoundEdges;
    @XmlAttribute
    protected String legendBorderAlpha;
    @XmlAttribute
    protected String bgColor;
    @XmlAttribute
    protected String borderColor;
    @XmlAttribute
    protected String canvasBgColor;
    @XmlAttribute
    protected String alternateHGridColor;
    @XmlAttribute
    protected String alternateVGridColor;
    @XmlAttribute
    protected String showShadow;
    @XmlAttribute
    protected String lineThickness;
    @XmlAttribute
    protected String canvasBorderThickness;
    @XmlAttribute
    protected String showPlotBorder;
    @XmlAttribute
    protected String canvasBaseDepth;
    @XmlAttribute
    protected String showLegend;
    @XmlAttribute
    protected String chartBottomMargin;

    /**
     * Gets the value of the set property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the set property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Set }
     * 
     * 
     */
    public List<Set> getSet() {
        if (set == null) {
            set = new ArrayList<Set>();
        }
        return this.set;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        if (caption == null) {
            return "";
        } else {
            return caption;
        }
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Gets the value of the subCaption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCaption() {
        if (subCaption == null) {
            return "";
        } else {
            return subCaption;
        }
    }

    /**
     * Sets the value of the subCaption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCaption(String value) {
        this.subCaption = value;
    }

    /**
     * Gets the value of the xAxisName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXAxisName() {
        if (xAxisName == null) {
            return "";
        } else {
            return xAxisName;
        }
    }

    /**
     * Sets the value of the xAxisName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXAxisName(String value) {
        this.xAxisName = value;
    }

    /**
     * Gets the value of the yAxisName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYAxisName() {
        if (yAxisName == null) {
            return "";
        } else {
            return yAxisName;
        }
    }

    /**
     * Sets the value of the yAxisName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYAxisName(String value) {
        this.yAxisName = value;
    }

    /**
     * Gets the value of the rotateYAxisName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRotateYAxisName() {
        if (rotateYAxisName == null) {
            return "1";
        } else {
            return rotateYAxisName;
        }
    }

    /**
     * Sets the value of the rotateYAxisName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRotateYAxisName(String value) {
        this.rotateYAxisName = value;
    }

    /**
     * Gets the value of the labelDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelDisplay() {
        if (labelDisplay == null) {
            return "Rotate";
        } else {
            return labelDisplay;
        }
    }

    /**
     * Sets the value of the labelDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelDisplay(String value) {
        this.labelDisplay = value;
    }

    /**
     * Gets the value of the slantLabels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlantLabels() {
        if (slantLabels == null) {
            return "0";
        } else {
            return slantLabels;
        }
    }

    /**
     * Sets the value of the slantLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlantLabels(String value) {
        this.slantLabels = value;
    }

    /**
     * Gets the value of the shownames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShownames() {
        if (shownames == null) {
            return "1";
        } else {
            return shownames;
        }
    }

    /**
     * Sets the value of the shownames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShownames(String value) {
        this.shownames = value;
    }

    /**
     * Gets the value of the showvalues property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowvalues() {
        if (showvalues == null) {
            return "0";
        } else {
            return showvalues;
        }
    }

    /**
     * Sets the value of the showvalues property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowvalues(String value) {
        this.showvalues = value;
    }

    /**
     * Gets the value of the decimals property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimals() {
        if (decimals == null) {
            return "2";
        } else {
            return decimals;
        }
    }

    /**
     * Sets the value of the decimals property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimals(String value) {
        this.decimals = value;
    }

    /**
     * Gets the value of the decimalPrecision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalPrecision() {
        if (decimalPrecision == null) {
            return "0";
        } else {
            return decimalPrecision;
        }
    }

    /**
     * Sets the value of the decimalPrecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalPrecision(String value) {
        this.decimalPrecision = value;
    }

    /**
     * Gets the value of the numberPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberPrefix() {
        if (numberPrefix == null) {
            return "R$";
        } else {
            return numberPrefix;
        }
    }

    /**
     * Sets the value of the numberPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberPrefix(String value) {
        this.numberPrefix = value;
    }

    /**
     * Gets the value of the numberSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberSuffix() {
        if (numberSuffix == null) {
            return "R$";
        } else {
            return numberSuffix;
        }
    }

    /**
     * Sets the value of the numberSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberSuffix(String value) {
        this.numberSuffix = value;
    }
    
    /**
     * Gets the value of the formatNumberScale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatNumberScale() {
        if (formatNumberScale == null) {
            return "1";
        } else {
            return formatNumberScale;
        }
    }

    /**
     * Sets the value of the formatNumberScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatNumberScale(String value) {
        this.formatNumberScale = value;
    }

    /**
     * Gets the value of the inDecimalSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInDecimalSeparator() {
        if (inDecimalSeparator == null) {
            return ",";
        } else {
            return inDecimalSeparator;
        }
    }

    /**
     * Sets the value of the inDecimalSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInDecimalSeparator(String value) {
        this.inDecimalSeparator = value;
    }

    /**
     * Gets the value of the inThousandSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInThousandSeparator() {
        if (inThousandSeparator == null) {
            return ".";
        } else {
            return inThousandSeparator;
        }
    }

    /**
     * Sets the value of the inThousandSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInThousandSeparator(String value) {
        this.inThousandSeparator = value;
    }

    /**
     * Gets the value of the decimalSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalSeparator() {
        if (decimalSeparator == null) {
            return ",";
        } else {
            return decimalSeparator;
        }
    }

    /**
     * Sets the value of the decimalSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalSeparator(String value) {
        this.decimalSeparator = value;
    }

    /**
     * Gets the value of the thousandSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThousandSeparator() {
        if (thousandSeparator == null) {
            return ".";
        } else {
            return thousandSeparator;
        }
    }

    /**
     * Sets the value of the thousandSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThousandSeparator(String value) {
        this.thousandSeparator = value;
    }

    /**
     * Gets the value of the numberScaleValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberScaleValue() {
        if (numberScaleValue == null) {
            return "1000,1000,1000";
        } else {
            return numberScaleValue;
        }
    }

    /**
     * Sets the value of the numberScaleValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberScaleValue(String value) {
        this.numberScaleValue = value;
    }

    /**
     * Gets the value of the numberScaleUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberScaleUnit() {
        if (numberScaleUnit == null) {
            return " Mil, Milh\u00e3o, Bi";
        } else {
            return numberScaleUnit;
        }
    }

    /**
     * Sets the value of the numberScaleUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberScaleUnit(String value) {
        this.numberScaleUnit = value;
    }

    /**
     * Gets the value of the yAxisMinValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYAxisMinValue() {
        if (yAxisMinValue == null) {
            return "";
        } else {
            return yAxisMinValue;
        }
    }

    /**
     * Sets the value of the yAxisMinValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYAxisMinValue(String value) {
        this.yAxisMinValue = value;
    }

    /**
     * Gets the value of the yAxisMaxValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYAxisMaxValue() {
        if (yAxisMaxValue == null) {
            return "";
        } else {
            return yAxisMaxValue;
        }
    }

    /**
     * Sets the value of the yAxisMaxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYAxisMaxValue(String value) {
        this.yAxisMaxValue = value;
    }

    /**
     * Gets the value of the palette property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPalette() {
        if (palette == null) {
            return "2";
        } else {
            return palette;
        }
    }

    /**
     * Sets the value of the palette property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPalette(String value) {
        this.palette = value;
    }

    /**
     * Gets the value of the useRoundEdges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseRoundEdges() {
        if (useRoundEdges == null) {
            return "1";
        } else {
            return useRoundEdges;
        }
    }

    /**
     * Sets the value of the useRoundEdges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseRoundEdges(String value) {
        this.useRoundEdges = value;
    }

    /**
     * Gets the value of the legendBorderAlpha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegendBorderAlpha() {
        if (legendBorderAlpha == null) {
            return "0";
        } else {
            return legendBorderAlpha;
        }
    }

    /**
     * Sets the value of the legendBorderAlpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegendBorderAlpha(String value) {
        this.legendBorderAlpha = value;
    }

    /**
     * Gets the value of the bgColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgColor() {
        if (bgColor == null) {
            return "FFFFFF";
        } else {
            return bgColor;
        }
    }

    /**
     * Sets the value of the bgColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgColor(String value) {
        this.bgColor = value;
    }

    /**
     * Gets the value of the borderColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderColor() {
        if (borderColor == null) {
            return "FFFFFF";
        } else {
            return borderColor;
        }
    }

    /**
     * Sets the value of the borderColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderColor(String value) {
        this.borderColor = value;
    }

    /**
     * Gets the value of the canvasBgColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanvasBgColor() {
        if (canvasBgColor == null) {
            return "FFFFFF";
        } else {
            return canvasBgColor;
        }
    }

    /**
     * Sets the value of the canvasBgColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanvasBgColor(String value) {
        this.canvasBgColor = value;
    }

    /**
     * Gets the value of the alternateHGridColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateHGridColor() {
        if (alternateHGridColor == null) {
            return "FFFFFF";
        } else {
            return alternateHGridColor;
        }
    }

    /**
     * Sets the value of the alternateHGridColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateHGridColor(String value) {
        this.alternateHGridColor = value;
    }

    /**
     * Gets the value of the alternateVGridColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateVGridColor() {
        if (alternateVGridColor == null) {
            return "FFFFFF";
        } else {
            return alternateVGridColor;
        }
    }

    /**
     * Sets the value of the alternateVGridColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateVGridColor(String value) {
        this.alternateVGridColor = value;
    }

    /**
     * Gets the value of the showShadow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowShadow() {
        if (showShadow == null) {
            return "1";
        } else {
            return showShadow;
        }
    }

    /**
     * Sets the value of the showShadow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowShadow(String value) {
        this.showShadow = value;
    }

    /**
     * Gets the value of the lineThickness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineThickness() {
        if (lineThickness == null) {
            return "2";
        } else {
            return lineThickness;
        }
    }

    /**
     * Sets the value of the lineThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineThickness(String value) {
        this.lineThickness = value;
    }

    /**
     * Gets the value of the canvasBorderThickness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanvasBorderThickness() {
        if (canvasBorderThickness == null) {
            return "1";
        } else {
            return canvasBorderThickness;
        }
    }

    /**
     * Sets the value of the canvasBorderThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanvasBorderThickness(String value) {
        this.canvasBorderThickness = value;
    }

    /**
     * Gets the value of the showPlotBorder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowPlotBorder() {
        if (showPlotBorder == null) {
            return "0";
        } else {
            return showPlotBorder;
        }
    }

    /**
     * Sets the value of the showPlotBorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowPlotBorder(String value) {
        this.showPlotBorder = value;
    }

    /**
     * Gets the value of the canvasBaseDepth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanvasBaseDepth() {
        if (canvasBaseDepth == null) {
            return "1";
        } else {
            return canvasBaseDepth;
        }
    }

    /**
     * Sets the value of the canvasBaseDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanvasBaseDepth(String value) {
        this.canvasBaseDepth = value;
    }

    /**
     * Gets the value of the showLegend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowLegend() {
        if (showLegend == null) {
            return "0";
        } else {
            return showLegend;
        }
    }

    /**
     * Sets the value of the showLegend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowLegend(String value) {
        this.showLegend = value;
    }

    /**
     * Gets the value of the chartBottomMargin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartBottomMargin() {
        if (chartBottomMargin == null) {
            return "0";
        } else {
            return chartBottomMargin;
        }
    }

    /**
     * Sets the value of the chartBottomMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartBottomMargin(String value) {
        this.chartBottomMargin = value;
    }

}
